version: '3'

services:
  db:
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    container_name: AdministradorDeLlavesDB
    volumes:
      - ./postgres:/var/lib/postgresql/data